version: '3.8'

services:
  chainbreaker:
    build:
      context: .
      dockerfile: Dockerfile.tools
    container_name: chainbreaker_app
    restart: always
    volumes:
      - /home/tiktoor/raw/chainbreaker:/app
    networks:
      - chainbreaker_net

networks:
  chainbreaker_net:
    driver: bridge

volumes:
