#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${CHAINBREAKER_INSTALL_E2E_IMAGE:-chainbreaker-install-e2e:local}"
INSTALL_URL="${CHAINBREAKER_INSTALL_URL:-https://chainbreaker.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
CHAINBREAKER_E2E_MODELS="${CHAINBREAKER_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e CHAINBREAKER_INSTALL_URL="$INSTALL_URL" \
  -e CHAINBREAKER_INSTALL_TAG="${CHAINBREAKER_INSTALL_TAG:-latest}" \
  -e CHAINBREAKER_E2E_MODELS="$CHAINBREAKER_E2E_MODELS" \
  -e CHAINBREAKER_INSTALL_E2E_PREVIOUS="${CHAINBREAKER_INSTALL_E2E_PREVIOUS:-}" \
  -e CHAINBREAKER_INSTALL_E2E_SKIP_PREVIOUS="${CHAINBREAKER_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
