export const browserCoreExamples = [
  "chainbreaker browser status",
  "chainbreaker browser start",
  "chainbreaker browser stop",
  "chainbreaker browser tabs",
  "chainbreaker browser open https://example.com",
  "chainbreaker browser focus abcd1234",
  "chainbreaker browser close abcd1234",
  "chainbreaker browser screenshot",
  "chainbreaker browser screenshot --full-page",
  "chainbreaker browser screenshot --ref 12",
  "chainbreaker browser snapshot",
  "chainbreaker browser snapshot --format aria --limit 200",
  "chainbreaker browser snapshot --efficient",
  "chainbreaker browser snapshot --labels",
];

export const browserActionExamples = [
  "chainbreaker browser navigate https://example.com",
  "chainbreaker browser resize 1280 720",
  "chainbreaker browser click 12 --double",
  'chainbreaker browser type 23 "hello" --submit',
  "chainbreaker browser press Enter",
  "chainbreaker browser hover 44",
  "chainbreaker browser drag 10 11",
  "chainbreaker browser select 9 OptionA OptionB",
  "chainbreaker browser upload /tmp/chainbreaker/uploads/file.pdf",
  'chainbreaker browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "chainbreaker browser dialog --accept",
  'chainbreaker browser wait --text "Done"',
  "chainbreaker browser evaluate --fn '(el) => el.textContent' --ref 7",
  "chainbreaker browser console --level error",
  "chainbreaker browser pdf",
];
